# Generated by Django 5.2 on 2025-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
